import { Button, VerticalBox, LineEdit} from "std-widgets.slint";
import "../resources/LXGWWenKaiGB-Regular.ttf";

component custom-lineedit inherits LineEdit {
    enabled: false;
    font-size: 14px;
    read-only: true;
    horizontal-alignment: center;
}

export component AppWindow inherits Window {
    //基本设置
    title: "文件处理工具";
    icon: @image-url("../resources/File.png");
    default-font-family: "霞鹜文楷等宽 GB";
    background: #111415;

    //按钮回调函数和属性
    //选择文件夹按钮
    callback select-folder();
    in property <string> new_folder_path: "选择需要处理的文件夹";
    //分类按钮
    callback organize();
    //重置按钮
    callback reposition();
    callback show-popup();
    //弹出的二级菜单那
    in-out property <string> message;
    callback show-popup-with-message(string);
    //布局
    VerticalLayout {
        padding: 20px;
        spacing: 20px;

        GridLayout {
            spacing: 10px;
            Row {
                Button {
                    width: 90px;
                    height: 40px;
                    text: "选择文件夹";
                    clicked => { root.select-folder(); }
                }

                selected-folder-path := custom-lineedit {
                    placeholder-text: root.new_folder_path;
                }
            }
        }

        GridLayout {
            spacing: 10px;
            Row {
                Button {
                    text: "删除LRF";
               
                }
                Button {
                    text: "归类(后缀)";
                }

                Button {
                    text: "归类(时间)";
                    clicked => {
                        root.organize();
                    }
                }
            }

            Row {
                Button {
                    text: "重置";
                    clicked => {
                        root.reposition();
                    }
                }
            }
        }
        popup := PopupWindow {
            x: parent.width / 2 - self.width / 2;
            y: parent.height / 2 - self.height / 2;
            height: 70px; 
            width: 70px;
            close-on-click: false;
            Rectangle { 
                height:100%; 
                width: 100%; 
                background: grey; 
                border-width: 1px;
                border-radius: 10px;
                border-color: blue;
            }
            
            VerticalBox {
                Text {
                    text: root.message;
                }
                Button {
                    text: "确定";
                    clicked => {
                        popup.close();
                    }
                }
            }
           
        }
    
    }

    show-popup-with-message(new-message) => {
        self.message = new-message;
        popup.show();
    }
}

